"""new fields in user model

Revision ID: 938a0c16a3b3
Revises: 4467dd937b20
Create Date: 2018-08-08 15:38:26.725567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938a0c16a3b3'
down_revision = '4467dd937b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
